<?php
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5b1ae1e9d350f',
		'title' => 'Options',
		'fields' => array(
			array(
				'key' => 'field_5b1ae1f4f00ea',
				'label' => 'Réseaux Social',
				'name' => 'reseaux_social',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'sub_fields' => array(
					array(
						'key' => 'field_5b1ae205f00eb',
						'label' => 'Facebook',
						'name' => 'facebook',
						'type' => 'url',
						'instructions' => 'Liens vers votre page Facebook',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b1ae233f00ec',
						'label' => 'Twitter',
						'name' => 'twitter',
						'type' => 'url',
						'instructions' => 'Liens vers votre page Twitter',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b1ae249f00ed',
						'label' => 'Google +',
						'name' => 'google-plus',
						'type' => 'url',
						'instructions' => 'Liens vers votre page Google Plus',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
          ),
          array(
						'key' => 'field_5b1ae250f00ee',
						'label' => 'Instagram',
						'name' => 'instagram',
						'type' => 'url',
						'instructions' => 'Liens vers votre page Instagram',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'options-orangea',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5b1a21a615e8d',
		'title' => 'Réglages de section',
		'fields' => array(
			array(
				'key' => 'field_5af29926db0d5',
				'label' => 'Sous-titre',
				'name' => '__org_subtitle',
				'type' => 'text',
				'instructions' => 'We felt that others might need it as well, so in this article we will show you how to add a secondary alternative title or subtitle in WordPress posts and pages.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'Sous-titre',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5af2cabc28aa5',
				'label' => 'General',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5af29fb5625c3',
				'label' => 'Type de section',
				'name' => '__org_type',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'about' => 'A Propos',
					'accommodation' => 'Hébergement',
					'activity' => 'Activités',
					'restaurant' => 'Restaurant',
					'galerie' => 'Galerie photo',
					'contact' => 'Réservation & Contact',
				),
				'default_value' => array(
				),
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5b1a4b4b57c5d',
				'label' => 'Elements',
				'name' => 'elements',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'sub_fields' => array(
					array(
						'key' => 'field_5af99eaca0134',
						'label' => 'Element ID',
						'name' => '__org_section_id',
						'type' => 'text',
						'instructions' => 'Apply unique ID to element to link directly to it by using #your_id (for element ID use lowercase input only).',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5af98e410b8a5',
						'label' => 'Extra class name',
						'name' => '__org_section_class',
						'type' => 'text',
						'instructions' => 'Add an extra class name to the element and refer to it from Custom CSS option.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5af98b09cf3d7',
						'label' => 'Activity Menu',
						'name' => '__org_activity_menu',
						'type' => 'select',
						'instructions' => 'Register menu location',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5af29fb5625c3',
									'operator' => '==',
									'value' => 'activity',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'activities_resort' => 'Activités Resort Menu',
							'activities_excursion' => 'Activités excursion Menu',
						),
						'default_value' => array(
						),
						'allow_null' => 1,
						'multiple' => 0,
						'ui' => 1,
						'ajax' => 1,
						'return_format' => 'value',
						'placeholder' => '',
					),
				),
			),
			array(
				'key' => 'field_5b1a6791aec6b',
				'label' => 'Activity Galeries',
				'name' => '__org_activity_galeries',
				'type' => 'gallery',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5af29fb5625c3',
							'operator' => '==',
							'value' => 'activity',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'min' => '',
				'max' => '',
				'insert' => 'append',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5b1a4be2c4c6e',
				'label' => 'Booking & Contact',
				'name' => 'booking_&_contact',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5af29fb5625c3',
							'operator' => '==',
							'value' => 'contact',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'sub_fields' => array(
					array(
						'key' => 'field_5af2ed64b05a0',
						'label' => 'Book Link',
						'name' => '__org_book_link',
						'type' => 'text',
						'instructions' => 'https://booking.ericsoft.com/BookingEngine/Book?idh=AEB9D8823D51317C&lang=fr&cur=EUR',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5af29fb5625c3',
									'operator' => '==',
									'value' => 'contact',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5af2eb7f95514',
						'label' => 'Informations (Contact)',
						'name' => '__org_info',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5af29fb5625c3',
									'operator' => '==',
									'value' => 'contact',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'visual',
						'toolbar' => 'basic',
						'media_upload' => 1,
						'delay' => 0,
					),
				),
			),
			array(
				'key' => 'field_5af2ca8a28aa4',
				'label' => 'Design Options',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5af2c94f9c099',
				'label' => 'Background Type',
				'name' => '__bg',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'color' => 'Fond de couleur',
					'image' => 'Fond d\'image',
					'galleries' => 'Fond galleries',
					'video' => 'Fond video',
				),
				'default_value' => array(
				),
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5b1a466d09eec',
				'label' => 'Background Galeries',
				'name' => '__org_bg_galeries',
				'type' => 'gallery',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5af2c94f9c099',
							'operator' => '==',
							'value' => 'galleries',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'min' => '',
				'max' => '',
				'insert' => 'append',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5af29a47db0d6',
				'label' => 'Background Image',
				'name' => '__org_bg_img',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5af2c94f9c099',
							'operator' => '==',
							'value' => 'image',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'preview_size' => 'full',
				'library' => 'all',
				'return_format' => 'array',
				'min_width' => 0,
				'min_height' => 0,
				'min_size' => 0,
				'max_width' => 0,
				'max_height' => 0,
				'max_size' => 0,
				'mime_types' => '',
			),
			array(
				'key' => 'field_5b1a46c459b0b',
				'label' => 'Background Styles',
				'name' => 'styles',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'sub_fields' => array(
					array(
						'key' => 'field_5af2c9b5c5e25',
						'label' => 'Background Color',
						'name' => '__org_bg_color',
						'type' => 'color_picker',
						'instructions' => 'Code de couleur',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5af2c94f9c099',
									'operator' => '==',
									'value' => 'image',
								),
							),
							array(
								array(
									'field' => 'field_5af2c94f9c099',
									'operator' => '==',
									'value' => 'color',
								),
							),
							array(
								array(
									'field' => 'field_5af2c94f9c099',
									'operator' => '==',
									'value' => 'galleries',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'transparent',
					),
					array(
						'key' => 'field_5b0b906666906',
						'label' => 'Background Size',
						'name' => '__org_bg_size',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5af2c94f9c099',
									'operator' => '==',
									'value' => 'image',
								),
							),
							array(
								array(
									'field' => 'field_5af2c94f9c099',
									'operator' => '==',
									'value' => 'galleries',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'cover' => 'Cover',
							'contain' => 'Contain',
							'initial' => 'Initial',
							'auto' => 'Auto',
						),
						'default_value' => array(
							0 => 'cover',
						),
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'ajax' => 0,
						'return_format' => 'value',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5af2c7c380e36',
						'label' => 'Background Position',
						'name' => '__org_bg_pos',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5af2c94f9c099',
									'operator' => '==',
									'value' => 'image',
								),
							),
							array(
								array(
									'field' => 'field_5af2c94f9c099',
									'operator' => '==',
									'value' => 'galleries',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'left' => 'Gauche',
							'left_top' => 'Gauche en haut',
							'left_bottom' => 'Gauche en bas',
							'left_center' => 'Gauche au milieu',
							'center' => 'Centrer',
							'center_top' => 'Centrer en haut',
							'center_bottom' => 'Centrer en bas',
							'right' => 'Droite',
							'right_top' => 'Droite en haut',
							'right_center' => 'Droite au milieu',
							'right_bottom' => 'Droite en bas',
						),
						'default_value' => array(
							0 => 'left_bottom',
						),
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'ajax' => 0,
						'return_format' => 'value',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b0b908e66907',
						'label' => 'Background Attachment',
						'name' => '__org_bg_attachment',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5af2c94f9c099',
									'operator' => '==',
									'value' => 'image',
								),
							),
							array(
								array(
									'field' => 'field_5af2c94f9c099',
									'operator' => '==',
									'value' => 'galleries',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'scroll' => 'Scroll',
							'fixed' => 'Fixed',
							'local' => 'Local',
						),
						'default_value' => array(
							0 => 'scroll',
						),
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'ajax' => 0,
						'return_format' => 'value',
						'placeholder' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => '__og_section',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5b1a21a643226',
		'title' => 'Réglage de la page d\'accueil',
		'fields' => array(
			array(
				'key' => 'field_5b0990920f919',
				'label' => 'Background',
				'name' => 'background',
				'type' => 'select',
				'instructions' => 'Background type',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'' => 'Aucun arrière-plan',
					'color' => 'Fond de couleur',
					'image' => 'Fond d\'image',
				),
				'default_value' => array(
					0 => ': Aucun arrière-plan',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
				'return_format' => 'value',
			),
			array(
				'key' => 'field_5b0990c40f91a',
				'label' => 'Background Color',
				'name' => 'bg_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
			),
			array(
				'key' => 'field_5b0991160f91b',
				'label' => 'Background Image',
				'name' => 'bg_image',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b0990920f919',
							'operator' => '==',
							'value' => 'image',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'preview_size' => 'full',
				'library' => 'all',
				'return_format' => 'array',
				'min_width' => 0,
				'min_height' => 0,
				'min_size' => 0,
				'max_width' => 0,
				'max_height' => 0,
				'max_size' => 0,
				'mime_types' => '',
			),
			array(
				'key' => 'field_5b09914e0f91c',
				'label' => 'Background Position',
				'name' => 'bg_position',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b0990920f919',
							'operator' => '==',
							'value' => 'image',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'left' => 'Gauche',
					'left_top' => 'Gauche en haut',
					'left_bottom' => 'Gauche en bas',
					'left_center' => 'Gauche au milieu',
					'center' => 'Centrer',
					'center_top' => 'Centrer en haut',
					'center_bottom' => 'Centrer en bas',
					'right' => 'Droite',
					'right_top' => 'Droite en haut',
					'right_center' => 'Droite au milieu',
					'right_bottom' => 'Droite en bas',
					'custom' => 'Autres position',
				),
				'default_value' => array(
					0 => 'left_top',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
				'return_format' => 'value',
			),
			array(
				'key' => 'field_5b099cfc14252',
				'label' => 'Custom Position',
				'name' => 'bg_custom_position',
				'type' => 'text',
				'instructions' => 'Personnaliser la position de l\'image de fond
e.g 0px 12px',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b09914e0f91c',
							'operator' => '==',
							'value' => 'custom',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5b0991800f91d',
				'label' => 'Background Size',
				'name' => 'bg_size',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b0990920f919',
							'operator' => '==',
							'value' => 'image',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'cover' => 'Cover',
					'contain' => 'Contain',
					'initial' => 'Initial',
					'auto' => 'Auto',
				),
				'default_value' => array(
					0 => 'cover',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
				'return_format' => 'value',
			),
			array(
				'key' => 'field_5b0991bb0f91e',
				'label' => 'Background Attachment',
				'name' => 'bg_attachment',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b0990920f919',
							'operator' => '==',
							'value' => 'image',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'scroll' => 'Scroll',
					'fixed' => 'Fixed',
					'local' => 'Local',
				),
				'default_value' => array(
					0 => 'fixed',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
				'return_format' => 'value',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
			),
		),
		'menu_order' => 2,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
		),
		'active' => 1,
		'description' => '',
	));

endif;